name: Lint Code with flake8

on:
  push:
    branches:
      - cd-pipeline  # Trigger linting on push to the cd-pipeline branch
  pull_request:
    branches:
      - cd-pipeline  # Trigger linting on pull requests targeting cd-pipeline

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 --count --max-complexity=10 --max-line-length=127 --statistics
