name: CD Pipeline to Render

on:
  push:
    branches:
      - main  # Triggers the workflow on push to main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your GitHub repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment (version 3.9)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run flake8 linting
    - name: Lint with flake8
      run: |
        flake8 --count --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t devops-capstone .

    # Step 6: Render auto-deploy note
    - name: Deploy to Render
      run: echo "Render auto-deploys from GitHub. No deploy step needed here."

